### ISSUE TITLE
[FEATURE] Support Multiline Strings

### ISSUE THREAD

**Issue by anewton1998** [ncomet/koson#11]
If a string contains newlines (i.e. it is a multiline string), the newlines are not escaped. Other JSON libraries will automatically replace the new lines with escaped newlines when serializing.

It would be great if this test would pass.

```
    @Test
    fun testMultilineString() {
        val multiline = """
            ------ BEGIN
            blah
            ------ END
        """.trimIndent()
        val json = obj {
            "line" to multiline
        }.toString()
        println(json)
        assertFalse(json.contains("\n"))
    }
```

**Comment by ncomet** [comment]
Thanks for the suggestion!

However, I don't see at all how one could achieve that (the lack of \n chars in the generated json). 
What would be the output of your `println(json)` ?
Because by using the multiline string template in Kotlin, you explicitly add newlines (\n) at the end of your lines, even if they don't show up in the language's syntax.

**Comment by ncomet** [comment]
If I understand this correctly, it should also work on all Strings. I'll try to work on it, thanks for the input !
